### ISSUE TITLE
Regarding unable to test domain RET12 and RET10

### ISSUE THREAD

**Issue by pradeepy555** [ONDC-Official/log-validation-utility#2]
I need to test RET10 domain and RET12 domain but utility giving error that domain must be RET11. How can I do test?

**"search_full_catalog_refresh": {
            "schemaErr0": "/context/domain must be equal to constant (ONDC:RET11)"
        }**

<img width="1225" alt="Screenshot 2023-11-06 at 1 00 28 PM" src="https://github.com/ONDC-Official/log-validation-utility/assets/8456136/4851e5a1-1199-429a-b863-098e0339fcca">

**Comment by sharmasahil0331** [comment]
Issue has been resolved 

@pradeepy555
