### ISSUE TITLE
RET:11 fulfillment_id issue in on_search_inc

### ISSUE THREAD

**Issue by killshotxd** [ONDC-Official/log-validation-utility#5]
We are not sending the bpp/fulfillment in the **on_search_inc** API as told by log validation utility now we are getting this error :

` "on_search_inc_refresh": {
            "prvdr0item0ff": "fulfillment_id in /bpp/providers[0]/items[0] should map to one of the fulfillments id in bpp/fulfillments"
        }`

**Comment by sharmasahil0331** [comment]
Issue has been resolved
